char **eff = (const char *){"BANK_SELECT_MSB",
														"MODULATIONWHEEL_MSB",
														"BREATH_MSB",
														"FOOT_MSB = 4",
														"PORTAMENTO_TIME_MSB",
														"DATA_ENTRY_MSB",
														"VOLUME_MSB",
														"BALANCE_MSB",
														"PAN_MSB = 10",
														"EXPRESSION_MSB",
														"EFFECTS1_MSB",
														"EFFECTS2_MSB",
														"GPC1_MSB = 16",
														"GPC2_MSB",
														"GPC3_MSB",
														"GPC4_MSB",
														"BANK_SELECT_LSB = 32",
														"MODULATIONWHEEL_LSB",
														"BREATH_LSB",
														"FOOT_LSB = 36",
														"PORTAMENTO_TIME_LSB",
														"DATA_ENTRY_LSB",
														"VOLUME_LSB",
														"BALANCE_LSB",
														"PAN_LSB = 42",
														"EXPRESSION_LSB",
														"EFFECTS1_LSB",
														"EFFECTS2_LSB",
														"GPC1_LSB = 48",
														"GPC2_LSB",
														"GPC3_LSB",
														"GPC4_LSB",
														"SUSTAIN_SWITCH = 64",
														"PORTAMENTO_SWITCH",
														"SOSTENUTO_SWITCH",
														"SOFT_PEDAL_SWITCH",
														"LEGATO_SWITCH",
														"HOLD2_SWITCH",
														"SOUND_CTRL1",
														"SOUND_CTRL2",
														"SOUND_CTRL3",
														"SOUND_CTRL4",
														"SOUND_CTRL5",
														"SOUND_CTRL6",
														"SOUND_CTRL7",
														"SOUND_CTRL8",
														"SOUND_CTRL9",
														"SOUND_CTRL10",
														"GPC5",
														"GPC6",
														"GPC7",
														"GPC8",
														"PORTAMENTO_CTRL",
														"FX_REVERB = 91",
														"FX_TREMOLO",
														"FX_CHORUS",
														"FX_CELESTE_DETUNE",
														"FX_PHASER",
														"DATA_ENTRY_INCR",
														"DATA_ENTRY_DECR",
														"NRPN_LSB",
														"NRPN_MSB",
														"RPN_LSB",
														"RPN_MSB",
														"ALL_SOUND_OFF = 120",
														"ALL_CTRL_OFF",
														"LOCAL_CONTROL",
														"ALL_NOTES_OFF",
														"OMNI_OFF",
														"OMNI_ON",
														"POLY_OFF",
														"POLY_ON"};